// This file initializes the dynamic library and connects it with the stub
// generated by flutter_rust_bridge_codegen.

import 'dart:ffi';

// import 'bridge_definitions.dart';
// export 'bridge_definitions.dart';

import 'bridge_generated.dart';
export 'bridge_generated.dart';
import 'dart:io' as io;

const _base = 'dptp_sdk';

// On MacOS, the dynamic library is not bundled with the binary,
// but rather directly **linked** against the binary.
final _dylib = io.Platform.isWindows ? '$_base.dll' : 'lib$_base.so';
final dylib = loadDylib(_dylib);
final DptpSdk sdk = DptpSdkImpl(dylib);

DynamicLibrary loadDylib(String path) => io.Platform.isIOS
    ? DynamicLibrary.process()
    : io.Platform.isMacOS && Abi.current() == Abi.macosX64
    ? DynamicLibrary.executable()
    : DynamicLibrary.open(path);
