[chain]
chain_id = 421613
rpc_urls = [
    "https://snowy-dimensional-wave.arbitrum-goerli.quiknode.pro/5fb1a4cbaec64e964facf89b037dabd44bd73b27/",
]
multicall_address = "0x1fb9057314f4460a673014F2AF84f3962381E453"

[contract_address]
vault = "0x0ee5Cd3b12870F13670C4C97316D7C59b68a0e75"
plp_manager = "0xA32585e3ecF1067F7E444a7ea3c0d6b5B21626F6"
plp_token = "0xbf3d20e4b16C10A63144bCe84a23CC8B24CbAf2C"

reward_tracker_fee_plp = "0xbC442C3CE3ebDbd44e66CF14aA22095Cc9378ff8"
reward_router = "0x3c5c6B99890Cb612Fb87ee05efFb867987537D6A"
vester_plp = "0x5F26E7D302FEa1F8A1827E5d208040138c69B281"
futurx_gateway = "0xd030Ae8EaDb30f6C44F036E7b35827Ac19409Df8"


[[contract_spender]]
address = "0xA32585e3ecF1067F7E444a7ea3c0d6b5B21626F6"
name = "lp_manager"

[[contract_spender]]
address = "0xd030Ae8EaDb30f6C44F036E7b35827Ac19409Df8"
name = "futurx_gateway"


[[tokens]]
chain_id = 421613
address = "0x6a9b98aA950c99300ca8Fa074C0D7FaCc9a8191B"
symbol = "USDT"
decimals = 18
name = "USD-Tether"
is_whitlisted = true
is_tradeable = true
quote_precision = 4
logo_url = "https://tokens.pancakeswap.finance/images/0x55d398326f99059fF775485246999027B3197955.png"


[[tokens]]
chain_id = 421613
address = "0x8Fb133239b2A3dfF78C15Bc2Ae6329ffCf9482f4"
symbol = "BTC"
decimals = 18
name = "Bitcoin"
is_whitelisted = true
is_tradeable = true
quote_precision = 8
logo_url = "https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"


[[tokens]]
chain_id = 421613
address = "0xb7455AcaFE37F38694880483BC3f48e49Ff53a87"
symbol = "DAI"
decimals = 18
name = "DAI Token"
is_whitlisted = true
is_tradeable = true
quote_precision = 4
logo_url = "https://s2.coinmarketcap.com/static/img/coins/64x64/4943.png"

#
#[[tokens]]
#chain_id = 421613
#address = "0x8557e89E7F86479bA8C55DA4257f7D2FA5030C8a"
#symbol = "BUSD"
#decimals = 18
#name = "Binance USD"
#is_whitlisted = true
#is_tradeable = true
#quote_precision = 4
#logo_url = "https://s2.coinmarketcap.com/static/img/coins/64x64/4687.png"


[[tokens]]
chain_id = 421613
address = "0x471385598B0Bdb63C89082F4166C0577C6C0263a"
symbol = "ETH"
decimals = 18
name = "Ethereum"
is_whitlisted = true
is_tradeable = true
quote_precision = 8
logo_url = "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png"

[[tokens]]
chain_id = 421613
address = "0xbf3d20e4b16C10A63144bCe84a23CC8B24CbAf2C"
symbol = "PLP"
decimals = 18
name = "Position LP"
is_whitelisted = true
is_tradeable = false
quote_precision = 4
logo_url = "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/smartchain/assets/0x5CA42204cDaa70d5c773946e69dE942b85CA6706/logo.png"

[[tokens]]
chain_id = 421613
address = "0xbC442C3CE3ebDbd44e66CF14aA22095Cc9378ff8"
symbol = "fPLP"
decimals = 18
name = "Fee PLP"
is_whitelisted = true
is_tradeable = false
quote_precision = 4
logo_url = ""