[chain]
chain_id = 97
rpc_urls = [
    "https://wandering-billowing-market.bsc-testnet.quiknode.pro/0180a2362b61879f20d7a51b504ad634b17eda4a/",
    # "https://rpc.ankr.com/bsc_testnet_chapel",
    # "https://data-seed-prebsc-2-s1.binance.org:8545/",
    # "https://data-seed-prebsc-1-s2.binance.org:8545/",
    # "https://data-seed-prebsc-1-s3.binance.org:8545/",
    # "https://data-seed-prebsc-2-s3.binance.org:8545/"
]
multicall_address = "0x6e5bb1a5ad6f68a8d7d6a5e47750ec15773d6042"

[contract_address]
vault = "0x6c580ed53a3eaa02841A9E8E360Bc6C37F469DBC"
plp_manager = "0xDF49C2d458892B681331F4EEC0d09A88b283f444"
plp_token = "0x792bA5e9E0Cd15083Ec2f58E434d875892005b91"
reward_tracker_fee_plp = "0x50C121Da29CBD8bD96Bdb6c6965F93F09C2Fc598"
reward_router = "0x51E97bb1e3fc16fEC95d02D301D0917304da3dc4"
vester_plp = "0x1eD5051bbFA6B80f30D50D14761634eBb770f024"
futurx_gateway = "0x7f8cd121aedd5249a03328ce792c6fc5a7f224ce"

[[contract_spender]]
address = "0xDF49C2d458892B681331F4EEC0d09A88b283f444"
name = "lp_manager"

[[contract_spender]]
address = "0x7f8cd121aedd5249a03328ce792c6fc5a7f224ce"
name = "futurx_gateway"


[[tokens]]
chain_id = 97
address = "0x542E4676238562b518B968a1d03626d544a7BCA2"
symbol = "USDT"
decimals = 18
name = "USD-Tether"
is_whitlisted = true
is_tradeable = true
quote_precision = 4
logo_url = "https://tokens.pancakeswap.finance/images/0x55d398326f99059fF775485246999027B3197955.png"


[[tokens]]
chain_id = 97
address = "0xc4900937c3222CA28Cd4b300Eb2575ee0868540F"
symbol = "BTC"
decimals = 18
name = "Bitcoin"
is_whitelisted = true
is_tradeable = true
quote_precision = 8
logo_url = "https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"


[[tokens]]
chain_id = 97
address = "0xB202545C693631eEeBC83E600c74cFf4EE54F39c"
symbol = "DAI"
decimals = 18
name = "DAI Token"
is_whitlisted = true
is_tradeable = true
quote_precision = 4
logo_url = "https://s2.coinmarketcap.com/static/img/coins/64x64/4943.png"


[[tokens]]
chain_id = 97
address = "0xb9838B8EeD90731e44733881a04D275Eb4064288"
symbol = "BUSD"
decimals = 18
name = "Binance USD"
is_whitlisted = true
is_tradeable = true
quote_precision = 4
logo_url = "https://s2.coinmarketcap.com/static/img/coins/64x64/4687.png"


[[tokens]]
chain_id = 97
address = "0x4D906559B2cEbBe063757ab76c5620C2149e4b0D"
symbol = "ETH"
decimals = 18
name = "Ethereum"
is_whitlisted = true
is_tradeable = true
quote_precision = 8
logo_url = "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png"

[[tokens]]
chain_id = 97
address = "0x792bA5e9E0Cd15083Ec2f58E434d875892005b91"
symbol = "PLP"
decimals = 18
name = "Position LP"
is_whitelisted = true
is_tradeable = false
quote_precision = 4
logo_url = "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/smartchain/assets/0x5CA42204cDaa70d5c773946e69dE942b85CA6706/logo.png"

[[tokens]]
chain_id = 97
address = "0x50C121Da29CBD8bD96Bdb6c6965F93F09C2Fc598"
symbol = "fPLP"
decimals = 18
name = "Fee PLP"
is_whitelisted = true
is_tradeable = false
quote_precision = 4
logo_url = ""
