[chain]
chain_id = 97
rpc_urls = ["https://data-seed-prebsc-1-s1.binance.org:8545/"]
multicall_address = ""


[[tokens]]
chain_id = 97
address = "0x0d8775f648430679a709e98d2b0cb6250d2887ef"
symbol = "Test"
decimals = 18
name = "Test"
is_whitlisted = true

[[tokens]]
chain_id = 97
address = "0x0d8775f648430679a709e98d2b0cb6250d2887ef"
symbol = "Test2"
decimals = 18
name = "Test 2"
is_whitelisted = true

